# Generated by Django 4.1.1 on 2022-09-30 18:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('data_emprestimo', models.DateTimeField(auto_now=True)),
                ('prazo', models.DurationField(default=datetime.timedelta(days=7))),
                ('data_devolucao', models.DateTimeField(null=True)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emprestimo_livros.livro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emprestimo_livros.usuario')),
            ],
        ),
    ]
