# Generated by Django 4.1.1 on 2022-09-30 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo_livros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='emprestimo',
            table='emprestimos',
        ),
        migrations.AlterModelTable(
            name='livro',
            table='livros',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuarios',
        ),
    ]
